Enable_header_links:
  default: true
  description:
    en: "Check this if you want to see the header links"
Base_url:
  default: "https://pulse-game.com/"
  description:
    en: "The base URL of the homepage, used in links."

Enable_footer:
  default: true
  description:
    en: "Uncheck this if you want to hide the footer"
Heading:
  default: ""
  max: 25
  description:
    en: "Text for the heading in the footer - you can use your site name for example - Max length 25 characters"
Blurb:
  default: ""
  max: 180
  description:
    en: "Enter a short blurb about your community - Max length 180 characters"
Link_sections:
  type: list
  list_type: simple
  default: "Design, Get inspired!|Code, Learn new things!|Business, Start a new career!|Shop, Buy cool stuff!|Community, The latest news about the people you care about!|World, Check out what's happening"
  description:
    en: "Add link sections. The ideal number of sections is six. One item per line in this order:<br> Text, title<br><b>Text:</b> what appears on in the footer<br><b>Title:</b> the text that appears when the item is hovered."
Links:
  type: list
  list_type: simple
  default: "Design, Design process, #, blank, Learn the basics|Design, Blog design, #, blank, What makes for a great blog?|Design, Photoshop tutorials, #, blank, Photoshop for beginners|Design, Design trends, #, blank, Stay on top of the current trends!|Code, Wordpress, #, blank, Wordpress code examples|Code, Tools, #, blank, Tools that will make your life easier!|Code, Tutorials, #, blank, Just starting out? We'll guide you through the basics|Business, Blogging, #, blank, Why not start a blog?|Business, Social media, #, blank, Learn how to leverage Social media and make it work for your business|Business, Make money, #, blank, Everyone likes to be paid!|Business, Marketing, #, blank, No business will survive without customers...Here's how to get'em!|Shop, Vectors, #, blank, buy vectors|Shop, Textures, #, blank, buy textures|Shop, UI kits, #, blank, buy UI kits|Shop, PSDs, #, blank, Ready-made PSD's|Community, Your corner, #, blank, Tell us how you feel!|Community, Questions, #, blank, Feel like answering some questions?|Community, Members, #, blank, Say hi to new members|Community, trending, #, blank, Catch up with the latest trending topics!|World, Politics, #, blank, Stay up to date|World, Education, #, blank, The latest research|World, Automotive, #, blank, We cover the latest models!|World, Sports, #, The latest scores|World, Tech, #, Never miss a new gadget"
  description:
    en: "Add links to link sections. One item per line in this order:<br>Parent, text, URL, target, title<br>It is a good idea to keep the number of links under each section similar<br><b>Parent:</b> the name of the parent section which this link shows under. Use the `text` value from the list above<br><b>Text:</b> the text that shows for this link<br><b>URL:</b> the path this item links to. You can use relative paths as well.<br><b>Target:</b> Choose whether this item will open in a new tab or in the same tab. Use blank to open the link in a new tab, or use self to open it in the same tab.<br><b>Title:</b> the text that shows when the link is hovered."
Small_links:
  type: list
  list_type: simple
  default: "Recruit A Friend, https://pulse-game.com/recruit-a-friend, self|Exchange, #, self| Merch, https://pulse-game.com/merch, self"
  description:
    en: "You can add small links at the bottom of the footer like Terms of Service and Privacy. One item per line in this order:<br>Text, URL, target<br><b>Text:</b> The text that shows for the small link<br><b>URL:</b> The path of the link<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab"
Social_links:
  type: list
  list_type: simple
  default: "Discord, Join the community on Discord, https://discord.com/invite/qjJZWza, blank,fab-discord| Reddit, Discuss on Reddit, https://reddit.com, blank,fab-reddit| Twitch, Follow us on Twitch, https://twitch.tv, blank,fab-twitch| Youtube, Check out our latest videos on Youtube, https://youtube.com, blank,fab-youtube| TikTok, Check out our latest videos on Tiktok, https://tiktok.com, blank,fab-tiktok| Twitter, show some love on Twitter, https://twitter.com, blank,fab-twitter| Facebook, Join us on Facebook, https://facebook.com, blank,fab-facebook| Instagram, View us on Instagram, https://instagram.com, blank,fab-instagram"
  description:
    en: "Enter the social links you'd like to add to the footer in this format:<br> provider, title, URL, target<br><b>Provider:</b> is the name of the provider like Facebook or Twitter<br><b>Title:</b> The text that shows when the link is hovered<br><b>URL:</b> The path you'd like the link to have<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab<br><b>Icon:</b> use a FontAwesome5 icon name (brand icons need a 'fab-' prefix)."
Show_footer_on_login_required_page:
  default: true
  description:
    en: "Check this setting if you want the footer to be displayed on the login-required page (only applies if your site is private)"
svg_icons:
  default: "fab-discord|fab-reddit|fab-twitch|fab-youtube|fab-tiktok|fab-twitter|fab-facebook|fab-instagram|fab-house|fab-gamepad"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in the social links setting above. "